# Generated by Django 3.2.5 on 2021-07-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='user_id',
        ),
    ]
