# Generated by Django 3.2.5 on 2021-07-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210709_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
